const config = {
  poolapiurl: "https://mineit.io/api/",
  algos: {
    "asic/fgpa": [
      "x16r",
      "x16rv2",
      "sha256d",
      "scrypt",
      "x11",
      "quark",
      "skunkhash",
      "cryptonight",
      "lyra2rev2",
    ],
    cpu: [
      "randomx",
      "yespower",
      "yescript",
      "argon2d",
      "argon2i",
      "yespower-litb",
    ],
    gpu: [
      "x16rv2",
      "neoscrypt",
      "ethash",
      "x25x",
      "progpow",
      "mtp",
      "x21s",
      "x16rt",
      "x16s",
      "x17",
      "x15",
      "x14",
      "x13",
      "blake2b",
      "blake2s",
      "keccak",
      "allium",
      "tribus",
      "xevan",
      "hex",
      "phi2",
      "c11",
      "hmq1725",
      "progpow",
      "cuckoo",
      "timetravel",
    ],
  },
};
module.exports = config;
